# Datos hardcodeados de una corrida real de la simulación.
# Se usan temporalmente para que el frontend pueda avanzar
# mientras el endpoint real (lectura desde BDD) no está terminado.
#
# El formato de cada fila respeta las claves que devolverá el endpoint
# definitivo (mismas columnas que la tabla `simulacion`).

MOCK_FILAS_SIMULACION: list[dict] = [
    {
        "hora": "10:00:00", "evento": "Abre Tienda",
        "rnd_llegada": 0.513, "tiempo_entre_llegadas": "00:32:23", "proxima_llegada": "10:32:23",
        "estado_tecnico": "libre",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 0,
        "tiempo_de_atencion": "", "tiempo_de_reparacion": "",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "10:32:23", "evento": "Llega_Cliente",
        "rnd_llegada": 0.113, "tiempo_entre_llegadas": "00:05:24", "proxima_llegada": "10:37:46",
        "estado_tecnico": "atendiendo_cliente",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 2, "cola_equipos_cantidad": 0,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "10:37:46", "evento": "Llega_Cliente",
        "rnd_llegada": 0.905, "tiempo_entre_llegadas": "01:45:55", "proxima_llegada": "12:23:42",
        "estado_tecnico": "atendiendo_cliente",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 3, "cola_equipos_cantidad": 0,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "10:54:51", "evento": "Fin_Atencion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "12:23:42",
        "estado_tecnico": "atendiendo_cliente",
        "rnd_duracion_atencion": 0.9387432325483114, "duracion_atencion": "00:19:23", "proximo_fin_atencion": "12:23:42",
        "rnd_presupuesto": 0.225, "presupuesto": "Elevado",
        "rnd_deja_para_reparar": 0.289, "deja_para_reparar": False,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 2, "cola_equipos_cantidad": 0,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "11:14:14", "evento": "Fin_Atencion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "12:23:42",
        "estado_tecnico": "atendiendo_cliente",
        "rnd_duracion_atencion": 0.7608855081743368, "duracion_atencion": "00:17:37", "proximo_fin_atencion": "12:23:42",
        "rnd_presupuesto": 0.764, "presupuesto": "Normal",
        "rnd_deja_para_reparar": 0.289, "deja_para_reparar": True,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 1, "cola_equipos_cantidad": 1,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "11:31:51", "evento": "Fin_Atencion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "12:23:42",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": 0.395, "presupuesto": "Normal",
        "rnd_deja_para_reparar": 0.289, "deja_para_reparar": True,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 2,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "12:27:48", "evento": "Fin_Reparacion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "12:23:42",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": 0.774, "duracion_reparacion": "02:13:51",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 1,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "14:13:44", "evento": "Llega_Cliente",
        "rnd_llegada": 0.129, "tiempo_entre_llegadas": "00:06:13", "proxima_llegada": "14:19:57",
        "estado_tecnico": "atendiendo_cliente",
        "rnd_duracion_atencion": 0.984, "duracion_atencion": "00:19:50", "proximo_fin_atencion": "14:33:34",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 1, "cola_equipos_cantidad": 1,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "14:19:57", "evento": "Llega_Cliente",
        "rnd_llegada": 0.827, "tiempo_entre_llegadas": "01:18:57", "proxima_llegada": "15:38:54",
        "estado_tecnico": "atendiendo_cliente",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 2, "cola_equipos_cantidad": 1,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "14:39:47", "evento": "Fin_Atencion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "15:38:54",
        "estado_tecnico": "atendiendo_cliente",
        "rnd_duracion_atencion": 0.7987394595892133, "duracion_atencion": "00:17:59", "proximo_fin_atencion": "15:38:54",
        "rnd_presupuesto": 0.875, "presupuesto": "Normal",
        "rnd_deja_para_reparar": 0.289, "deja_para_reparar": True,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 1, "cola_equipos_cantidad": 2,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "14:57:46", "evento": "Fin_Atencion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "15:38:54",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": 0.469, "presupuesto": "Normal",
        "rnd_deja_para_reparar": 0.289, "deja_para_reparar": True,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 3,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "16:16:44", "evento": "Llega_Cliente",
        "rnd_llegada": 0.695, "tiempo_entre_llegadas": "00:53:26", "proxima_llegada": "17:10:10",
        "estado_tecnico": "atendiendo_cliente",
        "rnd_duracion_atencion": 0.308, "duracion_atencion": "00:13:05", "proximo_fin_atencion": "16:29:48",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 1, "cola_equipos_cantidad": 3,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "16:29:48", "evento": "Fin_Atencion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "17:10:10",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": 0.126, "presupuesto": "Elevado",
        "rnd_deja_para_reparar": 0.901, "deja_para_reparar": True,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 4,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "17:23:14", "evento": "Llega_Cliente",
        "rnd_llegada": 0.29, "tiempo_entre_llegadas": "00:15:25", "proxima_llegada": "17:38:39",
        "estado_tecnico": "atendiendo_cliente",
        "rnd_duracion_atencion": 0.156, "duracion_atencion": "00:11:34", "proximo_fin_atencion": "17:34:48",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 1, "cola_equipos_cantidad": 4,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "17:34:48", "evento": "Fin_Atencion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "17:38:39",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": 0.202, "presupuesto": "Elevado",
        "rnd_deja_para_reparar": 0.99, "deja_para_reparar": True,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 5,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "17:36:16", "evento": "Fin_Reparacion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "17:38:39",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": 0.411, "duracion_reparacion": "00:47:38",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 4,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "17:51:41", "evento": "Llega_Cliente",
        "rnd_llegada": 0.638, "tiempo_entre_llegadas": "00:45:43", "proxima_llegada": "18:37:24",
        "estado_tecnico": "atendiendo_cliente",
        "rnd_duracion_atencion": 0.222, "duracion_atencion": "00:12:13", "proximo_fin_atencion": "18:03:54",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 1, "cola_equipos_cantidad": 4,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "18:03:54", "evento": "Fin_Atencion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "18:37:24",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": 0.548, "presupuesto": "Normal",
        "rnd_deja_para_reparar": 0.99, "deja_para_reparar": True,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 5,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "18:05:49", "evento": "Fin_Reparacion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "18:37:24",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": 0.008, "duracion_reparacion": "00:00:43",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 4,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "18:06:32", "evento": "Fin_Reparacion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "18:37:24",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": 0.67, "duracion_reparacion": "01:39:47",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 3,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "19:46:19", "evento": "Fin_Reparacion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "18:37:24",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": 0.438, "duracion_reparacion": "00:51:52",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 2,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "20:38:11", "evento": "Fin_Reparacion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "18:37:24",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": 0.716, "duracion_reparacion": "01:53:17",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 1,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
    {
        "hora": "22:31:28", "evento": "Fin_Reparacion",
        "rnd_llegada": -1, "tiempo_entre_llegadas": "", "proxima_llegada": "18:37:24",
        "estado_tecnico": "reparando",
        "rnd_duracion_atencion": -1, "duracion_atencion": "", "proximo_fin_atencion": "",
        "rnd_presupuesto": -1, "presupuesto": "",
        "rnd_deja_para_reparar": -1, "deja_para_reparar": None,
        "rnd_duracion_reparacion": -1, "duracion_reparacion": "",
        "cola_atencion_cantidad": 0, "cola_equipos_cantidad": 0,
        "tiempo_de_atencion": "00:00:00", "tiempo_de_reparacion": "00:00:00",
        "clientes_no_atendidos_por_cierre": 0,
    },
]